#!/usr/bin/env bash

# Change localhost to 127.0.0.2 and facebook.com to 8.8.8.8 in the /etc/hosts file

# Check if the script is running inside Docker
if grep -q docker /proc/1/cgroup; then
    # Modify the hosts file within the Docker container
    CONTAINER_ID=$(head -n 1 /proc/self/cgroup | cut -d '/' -f 3)
    docker exec $CONTAINER_ID sh -c "echo '127.0.0.2 localhost\n8.8.8.8 facebook.com' > /etc/hosts"
    echo "Changes applied within Docker container."
else
    # Modify the hosts file directly on the Ubuntu server
    sudo sed -i 's/^127\.0\.0\.1.*/127.0.0.2 localhost/' /etc/hosts
    sudo sed -i 's/^.*facebook\.com.*/8.8.8.8 facebook.com/' /etc/hosts
    echo "Changes applied on the host Ubuntu server."
fi
